version: "3.8"

services:
  app:
    image: node:18-alpine
    user: node
    command: sh -c "npm install && npm run start"
    working_dir: /app
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    ports:
      - 5747:5747
    environment:
      - AWS_REGION=eu-north-1
      - DYNAMODB_TABLE_NAME=status-info-api-StatusTable-local
      - DYNAMODB_ENDPOINT=http://dynamodb:8000
    depends_on:
      - dynamodb
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - 8000:8000
