export default {
  tableName: "Foo",
  simpleSchema: {
    id: "",
  },
  schema: {
    KeySchema: [
      {
        AttributeName: "id",
        KeyType: "HASH",
      },
    ],
    AttributeDefinitions: [
      {
        AttributeName: "id", // auto-generated hash
        AttributeType: "S",
        _AutoGenerated: {
          onEvents: ["create"],
          autoGenType: "uuidv4",
        },
      },
    ],
  },
  openapi: {
    schema: {
      type: "object",
      properties: {
        id: {
          description: "auto-generated uuidv4 hash",
          type: "string",
          example: "qwerty-12345-zappa-fr4nk-123456789",
        },
      },
    },
  },
};
