import { KnownAutoGeneratedTypes } from "../../lib/AWS/DynamoDB/DynamoDBORMTypes";
import { getEnumValues } from "../../utils/Transformations";

export enum AllowedStatusValues {
  "COMPLETED",
  "IN_PROGRESS",
  "FAILED",
  "CANCELLED",
}

// @see: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.NamingRulesDataTypes.html
export default {
  tableName: "StatusInfo",
  schema: {
    KeySchema: [
      {
        AttributeName: "id",
        KeyType: "HASH",
      },
    ],
    AttributeDefinitions: [
      {
        AttributeName: "id", // auto-generated uuid
        AttributeType: "S",
        _AutoGenerated: {
          onEvents: ["create"],
          autoGenType: "uuid" as KnownAutoGeneratedTypes,
        },
      },
      {
        AttributeName: "userId",
        AttributeType: "S",
      },
      {
        AttributeName: "userEmail",
        AttributeType: "S",
      },
      {
        AttributeName: "statusName",
        AttributeType: "S",
      },
      {
        AttributeName: "statusValue",
        AttributeType: "S",
        _AllowedValues: getEnumValues(AllowedStatusValues),
      },
      {
        AttributeName: "updatedAt", // auto-generated timestamp
        AttributeType: "S",
        _AutoGenerated: {
          onEvents: ["create", "update"],
          autoGenType: "timestamp" as KnownAutoGeneratedTypes,
          format: "iso",
        },
      },
    ],
  },
  openapi: {
    schema: {
      type: "object",
      properties: {
        id: {
          type: "string",
        },
        statusName: {
          type: "string",
        },
        statusValue: {
          type: "string",
        },
        userEmail: {
          type: "string",
        },
        updatedAt: {
          type: "string",
        },
      },
    },
  },
};
