import { BaseModel, Column, Table } from "../../services/AWS/DynamoDB/BaseDynamoDBableModel";
import { KnownAutoGeneratedTypes } from "../../services/AWS/DynamoDB/DynamoDBORMTypes";

// Luonnos, Lähetetty, Käsittelyssä, Odottaa täydentämistä, Valmis,
export enum KnownStatusValues {
  "SENT" = "Sent",
  "PROCESSING" = "Processing",
  "WAITING_FOR_COMPLETION" = "Waiting for completion",
  "READY" = "Ready",
}

@Table("StatusInfo")
export default class StatusInfo extends BaseModel {
  @Column({
    // auto-generated hash
    isPrimaryKeyType: "HASH",
    autoGenerated: {
      onEvents: ["create"],
      autoGenType: KnownAutoGeneratedTypes.uuidv5,
      autoGenFields: ["userId", "statusName"],
    },
    openapi: {
      description: "auto-generated uuidv5(userId, statusName) hash",
      example: "f1b0e8b0-5c5a-5b5a-9c9c-3c3c3c3c3c3c",
    },
  })
  id: string;

  @Column({
    openapi: {
      description: "user identification code",
      type: "string",
      example: "djregl-12345-mnccn-se4ax-123456789",
    },
  })
  userId: string;

  @Column({
    openapi: {
      description: "email of the user",
      type: "string",
      example: "test@mail.localhost",
    },
  })
  userEmail: string;

  @Column({
    openapi: {
      description: "programmic name of the status",
      example: "tax-return-status",
    },
  })
  statusName: string;

  @Column({
    allowedValues: Object.keys(KnownStatusValues),
    defaultValue: "SENT",
    openapi: {
      description: "value of the status",
      type: "string",
      enum: Object.keys(KnownStatusValues),
      default: "SENT",
    },
  })
  statusValue: string;

  @Column({
    // auto-generated timestamp
    autoGenerated: {
      onEvents: ["create"],
      autoGenType: KnownAutoGeneratedTypes.timestamp,
      format: "iso",
    },
    openapi: {
      description: "auto-generated timestamp: create time",
      format: "date-time",
    },
  })
  createdAt: string;

  @Column({
    // auto-generated timestamp
    autoGenerated: {
      onEvents: ["create", "update"],
      autoGenType: KnownAutoGeneratedTypes.timestamp,
      format: "iso",
    },
    openapi: {
      description: "auto-generated timestamp: last update time",
      format: "date-time",
    },
  })
  updatedAt: string;
}
