import { AttributeValue } from "@aws-sdk/client-dynamodb";

type PrimitiveDynamoDBRecord = Record<string, DDBPrimitive>;
type LooseDynamoDBRecord = Record<string, DDBPrimitive | AttributeValue>;
type DynamoDBRecord = Record<string, AttributeValue>;

type KnownAutoGeneratedTypes = "uuidv4" | "uuidv5" | "timestamp";
type DynamoDBModel = {
  tableName: string;
  schema: {
    AttributeDefinitions: Array<{
      AttributeName: string;
      AttributeType: string;
      _AutoGenerated?: {
        onEvents: Array<string>;
        autoGenType: KnownAutoGeneratedTypes;
        autoGenFields?: Array<string>;
        format?: string;
      };
      _AllowedValues?: Array<DDBPrimitive>;
      _DefaultValue?: DDBPrimitive;
    }>;
    KeySchema: Array<{ AttributeName: string; KeyType: string }>;
    GlobalSecondaryIndexes?: Array<{ IndexName: string; KeySchema: Array<{ AttributeName: string; KeyType: string }> }>;
    [key: string]: any;
  };
  openapi?: {
    schema: OpenAPIV3.SchemaObject;
  };
};

type DDBSearchClause = Array<{ key: string; value: DDBPrimitive; operator?: DDBOperator }>;

type DDBPrimitive = string | number | boolean | null | undefined;
type DDBOperator =
  | "="
  | "<>"
  | "<"
  | "<="
  | ">"
  | ">="
  | "BEGINS_WITH"
  | "BETWEEN"
  | "IN"
  | "CONTAINS"
  | "NOT_CONTAINS"
  | "ATTRIBUTE_EXISTS"
  | "ATTRIBUTE_NOT_EXISTS"
  | "ATTRIBUTE_TYPE"
  | "NULL"
  | "NOT_NULL";
