name: Build, Test, Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment where to deploy the stack (dev, staging)
        type: environment
        required: true
  workflow_call:
    inputs:
      environment:
        description: Environment where to deploy the stack (dev, staging)
        type: string
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  build-test-deploy:
    name: Build, test and deploy ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    outputs:
      url: ${{ steps.pulumi.outputs.url }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Build
        run: |
          npm install
          npm run build
      - name: Test
        run: |
          npm run test
      - name: prepare deployment
        run: |
          npm run build:infra
      - name: Get IAM role from Pulumi
        uses: Virtual-Finland-Development/pulumi-outputs-action@v1
        id: infra-iam-role
        with:
          organization: virtualfinland
          project: infrastructure
          stack: ${{ inputs.environment }}
          resource: DeployerIAMRole
          access-token: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: eu-north-1
          role-to-assume: ${{ steps.infra-iam-role.outputs.resource-output }}
          role-session-name: status-info-api-deploy
      - name: Deploy with Pulumi
        id: pulumi
        uses: pulumi/actions@v3
        with:
          work-dir: ./infra
          command: up
          stack-name: virtualfinland/${{ inputs.environment }}
          upsert: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      - name: Tag the deployment
        uses: Virtual-Finland-Development/automatic-release-action@v1.0
        if: ${{ inputs.environment == 'staging' }}
        with:
          environment: ${{ inputs.environment }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
