name: "Dev: build, test and deploy"
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy-dev:
    uses: Virtual-Finland-Development/status-info-api/.github/workflows/build-test-deploy.yml@main
    secrets: inherit
    with:
      environment: dev
